services:
  mongo:
    image: mongo:8.0.6-noble@sha256:8e70da4c1a64b280d641af1bc0edea6c1276bbe2d98b07ccbc2f2445286b34c3
    ports:
      - 27017:27017
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z@sha256:46b3009bf7041eefbd90bd0d2b38c6ddc24d20a35d609551a1802c558c1c958f
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data/minio --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - "bucket:/data:/data/minio"

volumes:
  bucket:
  data:
  node_modules:
